"""add_poster_key_to_serial_episodes

Revision ID: 3007e7b6a38a
Revises: 012
Create Date: 2026-05-10 04:26:59.774101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3007e7b6a38a'
down_revision = '012'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movies_search_vector', table_name='movies', postgresql_using='gin')
    op.add_column('serial_episodes', sa.Column('poster_key', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serial_episodes', 'poster_key')
    op.create_index('ix_movies_search_vector', 'movies', [sa.text("to_tsvector('simple'::regconfig, (COALESCE(name, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###